### ISSUE TITLE
does not work with gDNA table

### ISSUE THREAD

**Issue by baskarb1** [rosbashlab/TRIBE#1]
Hi,
I have been trying to use this pipeline to identify RNA edit sites using TRIBE in S2 cells. The example run as expected. My mRNA seq DATA gives me edit sites when I use the example gDNA table, but does not work when I generate my own gDNA table. The table is created fine in the mySQL database, and everything else seem to be good and even the final command gets completed, but the text file has zero edit sites displayed. 
When I try induced vs uninduced mRNA tables, it gives me several edit sites. I have tried generating the gDNA table several times with different data, but the problem presist. Please help.
Thanks
Baskar

**Comment by rosbashlab** [comment]
Hi,

It seems that the computational TRIBE is working for you, expect this problem with gDNA. I need more info from you to figure out what is going wrong. After the alignment to transcriptome/genome, both RNA and gDNA data uses identical scripts. So if you are able to successfully produce the matrix file, then load the data successfully to the mysql table, then error is likely in the variables that you have to provide in the rnaedit_gDNA_RNA.sh script: 
gDNAtablename="s2_gDNA"
gDNAexp="s2_gDNA"
gDNAtp="25"
Check to see if the variables above are set correctly. If this does not fix the problem for you, can you provide some sample output from the mysql table for gDNA and rnaedit_gDNA_RNA.sh script with the updated variables.

-Reazur

**Comment by rosbashlab** [comment]
The error was occurring because the sam file produced by genome alignment with bowtie2 was not sorted. I just added some code to sort the sam files in the shell script "trim_and_align_gDNA.sh". If you don't have the latest version of samtools, you might have to tweak the code a little.

I have updated the code on github to fix the bug. And, thank you for bringing this to my attention.
